name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Ensure Clean Environment
      - name: Clean Temporary Files
        run: |
          make clean clean-venv

      # Step 5: Install Dependencies
      - name: Install Dependencies
        run: |
          make venv
          source qpow-venv/bin/activate
          make install install-formatters

      # Step 6: Lint the Codebase
      - name: Lint the Codebase
        run: |
          source qpow-venv/bin/activate
          make lint

      # Step 7: Format the Codebase
      - name: Format the Codebase
        run: |
          source qpow-venv/bin/activate
          make format

      # Step 8: (Skip Testing Temporarily)
      # - name: Run Tests
      #   run: |
      #       source qpow-venv/bin/activate
      #       make test

      # Step 9: (Skip Coverage Temporarily)
      # - name: Generate Coverage Report
      #   run: |
      #       source qpow-venv/bin/activate
      #       make coverage

      # Step 10: Upload Coverage Report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_html
        if: always()

      # Step 11: Generate Documentation
      - name: Generate Documentation
        run: |
          source qpow-venv/bin/activate
          make docs

      # Step 12: Upload Documentation
      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs

      # Step 13: Final Cleanup
      - name: Clean Up
        run: |
          make clean clean-venv