name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up and install dependencies
      run: |
        make venv
        make install

    - name: Lint the codebase
      run: make lint

    - name: Run unit tests
      run: make test

    - name: Generate unit tests with Pynguin
      run: make generate-tests

    - name: Generate coverage report
      run: make coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov

    - name: Generate documentation with Doxygen
      run: make docs

    - name: Upload documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs

    - name: Clean temporary files
      run: make clean

    - name: Clean the virtual environment
      if: always()
      run: make clean-venv
