name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Clear Pip Cache
      run: make clear-cache

    - name: Create and Activate Virtual Environment
      run: |
        make venv
        source qpow-venv/bin/activate

    - name: Install Dependencies
      run: make install install-formatters

    - name: Lint the Codebase
      run: make lint

    - name: Format the Codebase
      run: make format

    - name: Run Tests
      run: make test

    - name: Generate Coverage Report
      run: make coverage

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage_html

    - name: Generate Documentation
      run: make docs

    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/html

    - name: Clean Up
      run: make clean clean-venv